import './globals.css'
import type { Metadata } from 'next'
// 导入类型定义，Metadata 类型可能用于定义页面元数据
import { Locale, i18n } from '@/i18n.config'
// 导入本地化（国际化）配置
import Header from './components/header'

import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
// 导入并设置 Inter 字体，这是一种谷歌字体，这里特别指定了使用拉丁字符子集

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}
// 设置页面元数据，这些信息可能用于 SEO 优化


export async function generateStaticParams() {
  return i18n.locales.map(locale => ({ lang: locale }))
}
// 生成静态路径参数的异步函数，这可能用于静态生成中的国际化

export default function RootLayout({
  children,
  //子组件
  params
  //参数，这里包含语言设置
}: {
  children: React.ReactNode
  params: { lang: Locale }
}) {
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <Header lang={params.lang} />
        <main>{children}</main>
      </body>
    </html>
    //<html lang={params.lang}> {/* 设置 HTML 标签的语言属性 */}
  )
}
